server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

spring:
  application:
    name: lotto-backend

  profiles:
    default: local

  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: lotto-backend
    description: 로또 번호 생성 마법진 백엔드 서버
    version: v1.0.0